FROM python:latest
WORKDIR /app/

COPY products/app.py /app/
COPY products/products.sql /app/
COPY key.txt /app/key.txt

RUN pip3 install flask
RUN pip3 install requests


ENV FLASK_APP=app.py


CMD ["flask", "run", "--host=0.0.0.0"]
